env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier/@typescript-eslint
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  '@typescript-eslint/prefer-interface': 0
  '@typescript-eslint/explicit-member-accessibility':
    - 1
    - accessibility: no-public
      overrides:
        parameterProperties: explicit
  '@typescript-eslint/no-parameter-properties': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/no-unused-vars':
    - 1
    - argsIgnorePattern: ^_|ignore
      varsIgnorePattern: ^_|ignore
overrides:
  - files: __tests__/**
    rules:
      no-console: 0
      react/jsx-uses-vars: 2
    plugins:
      - react
    env:
      jest: true
